## Predict Absenteeism using Logistic Regression 

### Import relevant libraries 

In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('./Datasets/data_preprocessed.csv')

In [3]:
data_preprocessed.head()

RT_1  RT_2  RT_3  RT_4  Month Value  Day of the Week        Date  \
0     0     0     0     1            7                1  2015-07-07   
1     0     0     0     0            7                1  2015-07-14   
2     0     0     0     1            7                2  2015-07-15   
3     1     0     0     0            7                3  2015-07-16   
4     0     0     0     1            7                3  2015-07-23   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## Creating Targets 

consider the median as prediction cut-off value; hours below median are considered moderate absenteesim and values above median are excessive

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(
    data_preprocessed['Absenteeism Time in Hours'] >
    data_preprocessed['Absenteeism Time in Hours'].median()
                   , 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets

In [8]:
data_preprocessed.head()

RT_1  RT_2  RT_3  RT_4  Month Value  Day of the Week        Date  \
0     0     0     0     1            7                1  2015-07-07   
1     0     0     0     0            7                1  2015-07-14   
2     0     0     0     1            7                2  2015-07-15   
3     1     0     0     0            7                3  2015-07-16   
4     0     0     0     1            7                3  2015-07-23   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

### Comment on targets 

In [9]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [10]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Date', 'Day of the Week', 'Daily Work Load Average', 'Distance to Work'], axis=1)

In [11]:
data_with_targets is data_preprocessed

False

In [12]:
data_with_targets.head()

RT_1  RT_2  RT_3  RT_4  Month Value  Transportation Expense  Age  \
0     0     0     0     1            7                     289   33   
1     0     0     0     0            7                     118   50   
2     0     0     0     1            7                     179   38   
3     1     0     0     0            7                     279   39   
4     0     0     0     1            7                     289   33   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

## Selecting inputs for the regression 

In [13]:
data_with_targets.shape

(700, 12)

In [14]:
data_with_targets.iloc[:,:14]

RT_1  RT_2  RT_3  RT_4  Month Value  Transportation Expense  Age  \
0       0     0     0     1            7                     289   33   
1       0     0     0     0            7                     118   50   
2       0     0     0     1            7                     179   38   
3       1     0     0     0            7                     279   39   
4       0     0     0     1            7                     289   33   
..    ...   ...   ...   ...          ...                     ...  ...   
695     1     0     0     0            5                     179   40   
696     1     0     0     0            5                     225   28   
697     1     0     0     0            5                     330   28   
698     0     0     0     1            5                     235   32   
699     0     0     0     1            5                     291   40   

     Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0                 30          0         2     1                      1  
1                 31          0         1     0                      0  
2                 31          0         0     0                      0  
3                 24          0         2     0                      1  
4                 30          0         2     1                      0  
..               ...        ...       ...   ...                    ...  
695               22          1         2     0                      1  
696               24          0         1     2                      0  
697               25          1         0     0                      1  
698               25          1         0     0                      0  
699               25          0         1     1                      0  

[700 rows x 12 columns]

In [15]:
data_with_targets.iloc[:,:-1]

RT_1  RT_2  RT_3  RT_4  Month Value  Transportation Expense  Age  \
0       0     0     0     1            7                     289   33   
1       0     0     0     0            7                     118   50   
2       0     0     0     1            7                     179   38   
3       1     0     0     0            7                     279   39   
4       0     0     0     1            7                     289   33   
..    ...   ...   ...   ...          ...                     ...  ...   
695     1     0     0     0            5                     179   40   
696     1     0     0     0            5                     225   28   
697     1     0     0     0            5                     330   28   
698     0     0     0     1            5                     235   32   
699     0     0     0     1            5                     291   40   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 11 columns]

In [16]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

## Standardize the data 

In [17]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    def __init__(self,columns):
        self.scaler = StandardScaler()
        self.columns = columns
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [18]:
unscaled_inputs.columns.values

array(['RT_1', 'RT_2', 'RT_3', 'RT_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [19]:
#columns_to_scale = ['Month Value', 'Day of the Week',
#       'Transportation Expense', 'Distance to Work', 'Age',
#       'Daily Work Load Average', 'Body Mass Index',
#       'Children', 'Pets']
columns_to_omit = ['RT1','RT_2','RT_3','RT_4','Education']
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [20]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [21]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\sayed\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\fromnumeric.py:3462: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


CustomScaler(columns=['RT_1', 'Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [22]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [23]:
scaled_inputs

RT_1  RT_2  RT_3  RT_4  Month Value  Transportation Expense  \
0   -0.577350     0     0     1     0.182726                1.005844   
1   -0.577350     0     0     0     0.182726               -1.574681   
2   -0.577350     0     0     1     0.182726               -0.654143   
3    1.732051     0     0     0     0.182726                0.854936   
4   -0.577350     0     0     1     0.182726                1.005844   
..        ...   ...   ...   ...          ...                     ...   
695  1.732051     0     0     0    -0.388293               -0.654143   
696  1.732051     0     0     0    -0.388293                0.040034   
697  1.732051     0     0     0    -0.388293                1.624567   
698 -0.577350     0     0     1    -0.388293                0.190942   
699 -0.577350     0     0     1    -0.388293                1.036026   

          Age  Body Mass Index  Education  Children      Pets  
0   -0.536062         0.767431          0  0.880469  0.268487  
1    2.130803         1.002633          0 -0.019280 -0.589690  
2    0.248310         1.002633          0 -0.919030 -0.589690  
3    0.405184        -0.643782          0  0.880469 -0.589690  
4   -0.536062         0.767431          0  0.880469  0.268487  
..        ...              ...        ...       ...       ...  
695  0.562059        -1.114186          1  0.880469 -0.589690  
696 -1.320435        -0.643782          0 -0.019280  1.126663  
697 -1.320435        -0.408580          1 -0.919030 -0.589690  
698 -0.692937        -0.408580          1 -0.919030 -0.589690  
699  0.562059        -0.408580          0 -0.019280  0.268487  

[700 rows x 11 columns]

In [24]:
scaled_inputs.shape

(700, 11)

## Split data into train & test and Shuffle 

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
train_test_split(scaled_inputs, targets)
#training dataset with inputs
#training dataset with target
#test dataset with inputs
# test data set with targets

[         RT_1  RT_2  RT_3  RT_4  Month Value  Transportation Expense  \
 154 -0.577350     0     1     0    -1.244823               -0.503235   
 508  1.732051     0     0     0     1.039256                0.190942   
 127 -0.577350     0     0     1    -1.530333               -1.574681   
 150 -0.577350     0     0     1    -1.244823                0.040034   
 166 -0.577350     0     0     1    -0.959313                0.568211   
 ..        ...   ...   ...   ...          ...                     ...   
 411 -0.577350     0     0     1    -0.959313                0.356940   
 538  1.732051     0     0     0     1.324766                0.190942   
 384  1.732051     0     0     0    -1.244823               -0.986140   
 179  1.732051     0     0     0    -0.959313               -0.654143   
 525  1.732051     0     0     0     1.039256                2.213108   
 
           Age  Body Mass Index  Education  Children      Pets  
 154 -0.536062        -0.408580          0  0.880469  1.1

In [27]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, shuffle=True, random_state = 20)

In [28]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [29]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)


## Logistic Regression with sklearn

In [30]:
from sklearn.linear_model import LogisticRegression 
from sklearn import metrics

### Training the model

In [31]:
reg = LogisticRegression()

In [32]:
reg.fit(x_train,y_train)

LogisticRegression()

In [33]:
reg.score(x_train,y_train)

0.7696428571428572

# Manually check the accuracy

In [34]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [35]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [36]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [37]:
np.sum((model_outputs==y_train))

431

In [38]:
model_outputs.shape[0]

560

In [39]:
np.sum((model_outputs==y_train))/model_outputs.shape[0]

0.7696428571428572

### finding intercept and coefficents

In [40]:
reg.intercept_

array([-1.16755845])

In [41]:
reg.coef_

array([[ 1.39693427,  1.12241598,  3.41098407,  1.15687133,  0.16540491,
         0.61972054, -0.17249658,  0.29075422, -0.21354365,  0.36308457,
        -0.27892662]])

In [42]:
feature_name = unscaled_inputs.columns.values

In [43]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                     RT_1     1.396934
1                     RT_2     1.122416
2                     RT_3     3.410984
3                     RT_4     1.156871
4              Month Value     0.165405
5   Transportation Expense     0.619721
6                      Age    -0.172497
7          Body Mass Index     0.290754
8                Education    -0.213544
9                 Children     0.363085
10                    Pets    -0.278927

In [44]:
summary_table.index = summary_table.index + 1 
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -1.167558
1                     RT_1     1.396934
2                     RT_2     1.122416
3                     RT_3     3.410984
4                     RT_4     1.156871
5              Month Value     0.165405
6   Transportation Expense     0.619721
7                      Age    -0.172497
8          Body Mass Index     0.290754
9                Education    -0.213544
10                Children     0.363085
11                    Pets    -0.278927

### Interpreting the coefficients

In [45]:
summary_table['Odd_ratio'] = np.exp(summary_table.Coefficient)
summary_table

Feature name  Coefficient  Odd_ratio
0                Intercept    -1.167558   0.311126
1                     RT_1     1.396934   4.042787
2                     RT_2     1.122416   3.072268
3                     RT_3     3.410984  30.295042
4                     RT_4     1.156871   3.179969
5              Month Value     0.165405   1.179871
6   Transportation Expense     0.619721   1.858409
7                      Age    -0.172497   0.841561
8          Body Mass Index     0.290754   1.337436
9                Education    -0.213544   0.807717
10                Children     0.363085   1.437757
11                    Pets    -0.278927   0.756595

In [46]:
summary_table.sort_values('Odd_ratio', ascending=False) ##odd ratio close to 1 means we should drop it 

Feature name  Coefficient  Odd_ratio
3                     RT_3     3.410984  30.295042
1                     RT_1     1.396934   4.042787
4                     RT_4     1.156871   3.179969
2                     RT_2     1.122416   3.072268
6   Transportation Expense     0.619721   1.858409
10                Children     0.363085   1.437757
8          Body Mass Index     0.290754   1.337436
5              Month Value     0.165405   1.179871
7                      Age    -0.172497   0.841561
9                Education    -0.213544   0.807717
11                    Pets    -0.278927   0.756595
0                Intercept    -1.167558   0.311126

## Testing the model

In [47]:
reg.score(x_test,y_test)

0.75

In [48]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.71585409, 0.28414591],
       [0.58616296, 0.41383704],
       [0.43295288, 0.56704712],
       [0.78613548, 0.21386452],
       [0.07394488, 0.92605512],
       [0.31703666, 0.68296334],
       [0.27899288, 0.72100712],
       [0.13196566, 0.86803434],
       [0.79020988, 0.20979012],
       [0.75266703, 0.24733297],
       [0.48752494, 0.51247506],
       [0.21729605, 0.78270395],
       [0.07103871, 0.92896129],
       [0.73380394, 0.26619606],
       [0.31813645, 0.68186355],
       [0.54875841, 0.45124159],
       [0.54641922, 0.45358078],
       [0.53469127, 0.46530873],
       [0.38154465, 0.61845535],
       [0.05280022, 0.94719978],
       [0.70139374, 0.29860626],
       [0.78613548, 0.21386452],
       [0.4021181 , 0.5978819 ],
       [0.4021181 , 0.5978819 ],
       [0.25547992, 0.74452008],
       [0.74839439, 0.25160561],
       [0.5075175 , 0.4924825 ],
       [0.86249055, 0.13750945],
       [0.20913881, 0.79086119],
       [0.78613548, 0.21386452],
       [0.

In [49]:
predicted_proba.shape #col1 -> target: 0 col2: target-> 1

(140, 2)

In [50]:
predicted_proba[:,1]

array([0.28414591, 0.41383704, 0.56704712, 0.21386452, 0.92605512,
       0.68296334, 0.72100712, 0.86803434, 0.20979012, 0.24733297,
       0.51247506, 0.78270395, 0.92896129, 0.26619606, 0.68186355,
       0.45124159, 0.45358078, 0.46530873, 0.61845535, 0.94719978,
       0.29860626, 0.21386452, 0.5978819 , 0.5978819 , 0.74452008,
       0.25160561, 0.4924825 , 0.13750945, 0.79086119, 0.21386452,
       0.36888002, 0.69793183, 0.70305188, 0.53602748, 0.21386452,
       0.54007251, 0.21772624, 0.72804425, 0.40843877, 0.61263541,
       0.20603208, 0.46388318, 0.23424104, 0.33215205, 0.84452053,
       0.55076251, 0.70977044, 0.28414591, 0.21358216, 0.19841409,
       0.59260693, 0.26464705, 0.68296334, 0.26500437, 0.84826849,
       0.43691889, 0.88295078, 0.22755558, 0.27259281, 0.28205669,
       0.71587501, 0.67265084, 0.29078134, 0.78679603, 0.20491216,
       0.26533177, 0.06263422, 0.21772624, 0.72124509, 0.30468007,
       0.21772624, 0.22916169, 0.91577265, 0.46647551, 0.60920

# Saving model

In [51]:
import pickle

In [52]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [53]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)